---
abstract: 'Use subincludes in your Catalyst views'
author:
  - 'Nilson Santos Figueiredo Junior, C<< <nilsonsfj at cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-Component-SubInclude
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Catalyst::Plugin::SubRequest: 0
  Catalyst::Runtime: 5.70000
  Moose: 0
  Moose::Role: 0
  namespace::clean: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.03
